In [ ]:
# Nötige Bibliotheken installieren

!pip3 install numpy pandas requests scipy

_Adapted from [Pandas Workshop](https://github.com/stefmolin/pandas-workshop)_

# 1. Einführung in Pandas

Wir beginnen mit der Vorstellung der Klassen **`Series`**, **`DataFrame`** und **`Index`**, welche die grundlegenden Bausteine der Pandas-Bibliothek darstellen, und zeigen, wie man mit ihnen arbeitet. 
Am Ende dieses Abschnitts werden Sie in der Lage sein, DataFrames zu erstellen und Operationen an ihnen durchzuführen, um die Daten zu inspizieren und zu filtern.

## 2. `DataFrame`s

Ein **DataFrame** besteht aus einder oder mehreren **Series**. 
Die Namen der **Series** stellen die Spalten dar, die Zeilen haben einen **Index**.

In [2]:
import pandas as pd

meteorites = pd.read_csv('data/Meteorite_Landings.csv', nrows=5)
meteorites

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

*Quelle: [NASA's Open Data Portal](https://data.nasa.gov/dataset/meteorite-landings)*

#### Series

In [3]:
meteorites.name

0      Aachen
1      Aarhus
2        Abee
3    Acapulco
4     Achiras
Name: name, dtype: object

#### Columns

In [4]:
meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

#### Index

In [5]:
meteorites.index

RangeIndex(start=0, stop=5, step=1)

## DataFrames erstellen

Wir können **DataFrames** aus einer Vielzahl von Quellen erstellen, wie zum Beispiel anderen **Python-Objekten**, **Flat Files**, **Webscraping** und **API-Anfragen**.
Hier werden wir nur ein paar Beispiele sehen, aber schauen Sie sich für eine vollständige Liste unbedingt [diese Seite](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) in der Dokumentation an.

### Using a flat file

In [ ]:
import pandas as pd

meteorites = pd.read_csv('../data/Meteorite_Landings.csv')

*Tip: There are many parameters to this function to handle some initial processing while reading in the file &ndash; be sure check out the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).*

### Daten von einer API verwenden

Das Projekt (OpenMensa)[https://openmensa.org] sammelt Informationen zu Standorten und Speiseplänen öffentlicher Mensen, und bietet diese als Javascript Object Notation (JSON) an.

In [ ]:
import requests

response = requests.get('https://openmensa.org/api/v2/canteens/')

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

mensen = pd.DataFrame(payload)
mensen.head(3)

,id,name,city,address,coordinates
0,1,Mensa UniCampus Magdeburg,Magdeburg,"Pfälzer Str. 1, 39106 Magdeburg","[52.139618827301895, 11.647599935531616]"
1,2,Magdeburg Herrenkurg,Magdeburg,"Breitscheidstr. 2, 39114 Magdeburg","[52.14006658530411, 11.67566657066345]"
2,3,Mensa Stendal,Stendal,"Osterburger Str. 25, 39567 Stendal","[52.615015758022146, 11.849302053451538]"

*Tip: `df.to_csv('data.csv')` schreibt diese Daten in `data.csv`.*

In [8]:
# erste 500 Mensen
response = requests.get('https://openmensa.org/api/v2/canteens/')

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

mensen = pd.DataFrame(payload)
mensen.head(3)

,id,name,city,address,coordinates
0,1,Mensa UniCampus Magdeburg,Magdeburg,"Pfälzer Str. 1, 39106 Magdeburg","[52.139618827301895, 11.647599935531616]"
1,2,Magdeburg Herrenkurg,Magdeburg,"Breitscheidstr. 2, 39114 Magdeburg","[52.14006658530411, 11.67566657066345]"
2,3,Mensa Stendal,Stendal,"Osterburger Str. 25, 39567 Stendal","[52.615015758022146, 11.849302053451538]"

In [ ]:
# /canteens/268/days/2025-11-11/meals/
response = requests.get('https://openmensa.org/api/v2/canteens/268/meals/')

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

essen = pd.DataFrame(payload)
essen

Request was not successful and returned code: 404.

Empty DataFrame
Columns: []
Index: []